"use client";
import { useState } from "react";
import Link from "next/link";
import { generateDocument, type GeneratePayload, type GeneratedDocument } from "../../lib/api";

const initial: GeneratePayload = { document_type: "notice", property_company: "", community_name: "", owner_name: "", property_address: "", overdue_amount: 0, overdue_period: "", contract_status: "已签订物业服务合同", payment_deadline: "", contact_phone: "" };

export default function GeneratePage() {
  const [form, setForm] = useState(initial); const [doc, setDoc] = useState<GeneratedDocument | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const update = (key: keyof GeneratePayload, value: string | number) => setForm((old) => ({ ...old, [key]: value }));
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(""); setLoading(true); try { setDoc(await generateDocument(form)); } catch (err) { setError(err instanceof Error ? err.message : "生成失败"); } finally { setLoading(false); } }
  return <main className="min-h-screen"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl justify-between px-6 py-4"><Link href="/" className="font-bold text-blue-700">物业易催款</Link><Link href="/" className="text-sm text-slate-500">返回首页</Link></div></header><div className="mx-auto grid max-w-6xl gap-8 px-6 py-10 lg:grid-cols-2"><form onSubmit={submit} className="rounded-xl bg-white p-6 shadow-sm"><h1 className="text-2xl font-bold">免费生成催缴文书</h1><p className="mt-2 text-sm text-slate-500">请填写真实、完整的信息，生成后请人工核验。</p><div className="mt-6 grid gap-4">{([["property_company","物业公司名称"],["community_name","小区名称"],["owner_name","业主姓名"],["property_address","房屋地址"],["overdue_period","欠费时间，如2025年1月至6月"],["payment_deadline","缴费期限（可选）"],["contact_phone","联系电话（可选）"]] as const).map(([key,label]) => <label key={key} className="grid gap-1 text-sm font-medium">{label}<input required={!key.includes("payment") && !key.includes("contact")} value={String(form[key])} onChange={(e) => update(key, e.target.value)} className="rounded-lg border border-slate-300 px-3 py-2 font-normal outline-none focus:border-blue-500" /></label>)}<label className="grid gap-1 text-sm font-medium">欠费金额（元）<input required type="number" min="0.01" step="0.01" value={form.overdue_amount || ""} onChange={(e) => update("overdue_amount", Number(e.target.value))} className="rounded-lg border border-slate-300 px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">文书类型<select value={form.document_type} onChange={(e) => update("document_type", e.target.value)} className="rounded-lg border border-slate-300 px-3 py-2 font-normal"><option value="notice">物业费催缴通知书</option><option value="deadline_notice">限期缴费通知书</option><option value="lawyer_letter">律师函草稿</option><option value="litigation_notice">起诉前告知书草稿</option></select></label><label className="grid gap-1 text-sm font-medium">服务合同情况<textarea value={form.contract_status} onChange={(e) => update("contract_status", e.target.value)} className="rounded-lg border border-slate-300 px-3 py-2 font-normal" rows={2} /></label></div>{error && <p className="mt-4 text-sm text-red-600">{error}</p>}<button disabled={loading} className="mt-6 w-full rounded-lg bg-blue-600 px-4 py-3 font-semibold text-white disabled:opacity-50">{loading ? "生成中…" : "生成文书"}</button></form><section className="rounded-xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">文书预览</h2>{doc ? <><div className="mt-4 flex justify-end"><button onClick={() => navigator.clipboard.writeText(doc.content)} className="rounded border px-3 py-2 text-sm">复制全文</button></div><pre className="mt-3 max-h-[620px] overflow-auto whitespace-pre-wrap rounded-lg bg-slate-50 p-5 text-sm leading-7">{doc.content}</pre><p className="mt-4 text-xs leading-5 text-slate-500">{doc.disclaimer}</p></> : <div className="mt-6 rounded-lg border-2 border-dashed border-slate-200 p-10 text-center text-slate-400">填写左侧信息后，文书将在这里显示</div>}</section></div></main>;
}
